const APP = {
  NAME: 'iLasan Agri System',
  VERSION: '0.3.0',
  TIMEZONE: 'Asia/Jakarta'
};

const SHEETS = {
  PETANI: 'PETANI',
  LAHAN: 'LAHAN',
  BLOK: 'BLOK',
  KOMODITAS: 'KOMODITAS',
  VARIETAS: 'VARIETAS',
  SIKLUS: 'SIKLUS',
  UNIT_BUDIDAYA: 'UNIT_BUDIDAYA',
  SOP: 'SOP',
  SOP_DETAIL: 'SOP_DETAIL',
  AKTIVITAS: 'AKTIVITAS',
  KEUANGAN: 'KEUANGAN',
  PANEN: 'PANEN',
  PASCAPANEN: 'PASCAPANEN',
  PEMASARAN: 'PEMASARAN',
  ASET: 'ASET',
  PENYUSUTAN: 'PENYUSUTAN'
};
